# Jekyll configuration for GitHub Pages
exclude:
  - minecraft-server/backend/
  - minecraft-server/mc-panel/
  - node_modules/
  - package.json
  - package-lock.json
  - .gitignore
  - .git/

# Include folders that start with underscore
include:
  - minecraft-server/_next
